// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/egandro/news-deframer/pkg/downloader (interfaces: Downloader)
//
// Generated by this command:
//
//	mockgen -destination=./mock_downloader/mocks.go github.com/egandro/news-deframer/pkg/downloader Downloader
//

// Package mock_downloader is a generated GoMock package.
package mock_downloader

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDownloader is a mock of Downloader interface.
type MockDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockDownloaderMockRecorder
	isgomock struct{}
}

// MockDownloaderMockRecorder is the mock recorder for MockDownloader.
type MockDownloaderMockRecorder struct {
	mock *MockDownloader
}

// NewMockDownloader creates a new mock instance.
func NewMockDownloader(ctrl *gomock.Controller) *MockDownloader {
	mock := &MockDownloader{ctrl: ctrl}
	mock.recorder = &MockDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloader) EXPECT() *MockDownloaderMockRecorder {
	return m.recorder
}

// DownloadRSSFeed mocks base method.
func (m *MockDownloader) DownloadRSSFeed(feed string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadRSSFeed", feed)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadRSSFeed indicates an expected call of DownloadRSSFeed.
func (mr *MockDownloaderMockRecorder) DownloadRSSFeed(feed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadRSSFeed", reflect.TypeOf((*MockDownloader)(nil).DownloadRSSFeed), feed)
}
