.PHONY: install build clean dev test dist lint lint-fix

install:
	npm install

dist:
	npm run dist

build:
	npm run build

clean:
	npm run clean

dev:
	npm run dev

test:
	npm run test

lint:
	npm run lint

lint-fix:
	npm run lint -- --fix
